const PRODUCTS_DATA = [
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp1",
        "price":  "424,4k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/3qLup065na",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Trang trí hồ cá Hồ cá Cây thủy sinh giả Bộ vỏ sò Tạo cảnh hồ cá Phụ kiện bể cá Cây nhựa resin Cho bể nuôi cá Cá cảnh Cá nhiệt đới Hồ cá tại nhà Set trang trí nhiều mẫu mã"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp2",
        "price":  "168,5k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/3g2Uch6j8Z",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá trang trí trang trí / Bể cá trang trí tường dây chuyền / Câu cá Weng trang trí / Câu cá nổi Người già Câu cá mở Bể cá trang trí cảnh quan"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp3",
        "price":  "81,2k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4AylDc4p7g",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Trang trí hồ cá / Cảnh vật thể nhỏ, đồ chơi nước chảy, trang trí cá vàng nhỏ, mô hình mô phỏng cá nhỏ, cảnh quan vi mô, cảnh quan cá nhỏ"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp4",
        "price":  "90,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/40fL1J5SSf",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Vi sinh bể cá PVN làm trong nước bể cá, khử độc, hạn chế bệnh cho cá Cá Cảnh Thiên Phước cho hồ cá thuỷ sinh, cá cảnh"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp5",
        "price":  "105,4k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4VbbcE3YRm",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Nhiệt kế bể cá cá cá cảnh cá cảnh cá cảnh 🇾 ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ 🇾 ❈ ❈ ❈ ❈ ❈ ❈ ❈ ❈ 🍎 PO66"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp6",
        "price":  "36,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4LIBPv4Bml",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Detox W+ khử Clo nước máy, giảm kim loại nặng hồ cá cảnh, cá Koi, cá vàng, cá rồng, cá la hán, cá betta, cá bảy màu"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp7",
        "price":  "35,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4qES0q2Hls",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Lồng đẻ cá 7 màu - Lồng ép cá đẻ - Lồng tách cá bằng mica cho cá Guppy, cá Mún, cá cảnh nhỏ size S,M,L."
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp8",
        "price":  "35,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4fv1oX2v6r",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Lồng đẻ cá 7 màu - Lồng dưỡng cá - Bể tách cá bằng mica cho cá Guppy, cá Mún, cá cảnh nhỏ size S,M,L."
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp9",
        "price":  "35,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/5ArIPS115y",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Lồng đẻ cá 7 màu - Lồng dưỡng cá - Lồng ép cá đẻ bằng mica cho cá Guppy, cá Mún, cá cảnh nhỏ size S,M,L."
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Bơm \u0026 Thiết Bị Lọc",
        "id":  "csv-sp10",
        "price":  "29,0k",
        "category":  "bom-loc",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/50XsD91eQx",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Khăn lọc bể cá - Thảm lọc hồ cá kiểng - bông lọc bể cá cảnh - Phụ kiện bể cá - Hồ cá cảnh - Bể thủy sinh"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp11",
        "price":  "100,6k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/BScSGK3F2",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá trang trí trang trí / Nhà trốn cá nhỏ / Cốc hút hút bể cá tường đám mây trốn nhà / Lỗ trốn tôm cá nhỏ / Bể sinh sản cá tổ cá nhà"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp12",
        "price":  "140,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/19CFxKga1",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Cảnh quan bể cá / Cảnh quan bể cá Xem hang động / Nhà sơ tán cá và tôm / hang sinh sản cá và tôm nhỏ / Rùa sáng tạo hang động ngầm Trang trí cảnh quan / Phụ kiện hồ cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp13",
        "price":  "51,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/W5SqsImZ8",
        "status":  "active",
        "rating":  "5.0",
        "title":  "LỒNG TÁCH CÁ CÁCH LY CÁ - LỐNG TÁCH CÁ ĐẺ CHO CÁ CẢNH - LỒNG TÁCH CÁ MẪU MỚI , LỒNG TÁC CÁ VUÔNG ,TRÒN ,MICA"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Bơm \u0026 Thiết Bị Lọc",
        "id":  "csv-sp14",
        "price":  "29,0k",
        "category":  "bom-loc",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/Lm2eZJPu7",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Túi lọc hồ cá - Tất lọc bể cá - Túi lọc bông - lọc cặn hồ cá - bể cá cảnh biển- Phụ kiện cá cảnh"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp15",
        "price":  "39,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/qiJFUHVtE",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Câu Cá Mèo Bể Cá Trang Trí Bể Cá Hangable Cảnh Quan Bể Cá Mèo Câu Cá Trang Trí Nhà Bể Cá Trang Trí"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp16",
        "price":  "87,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/gOt3BI9ED",
        "status":  "active",
        "rating":  "5.0",
        "title":  "WEOPCVBNF902 Trang trí bể cá cá cá có hiệu ứng phát sáng Đồ dùng bể cá cá thực vật Cảnh quan dưới nước Đồ trang trí bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp17",
        "price":  "39,1k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1BL9e6GFDK",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Lồng đẻ cá 7 màu -Lồng dưỡng cá -Lồng cá đẻ bằng mica cho Cá Guppy,Cá Mún, Cá Cảnh Nhỏ-nhiều size#"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp18",
        "price":  "84,7k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/111jRnGsYJ",
        "status":  "active",
        "rating":  "5.0",
        "title":  "[CENJ] Hành trình nhỏ dễ thương đến phương Tây Master And Apprentice Đồ trang trí bốn người Phong cảnh giả Cảnh quan bể cá Cảnh quan Đồ trang trí cảnh quan bể cá Cảnh quan vi mô [MỚI]"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp19",
        "price":  "25,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1Vy02iEyXQ",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Guouqna Bể Cá Trang Trí Mô Phỏng Thực Vật Thủy Sinh Cảnh Quan Cá Cảnh Cá Cá Cỏ Nhân Tạo Phụ Kiện Bể Cá GUOUqna"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Đèn LED \u0026 Thủy Sinh",
        "id":  "csv-sp20",
        "price":  "195,2k",
        "category":  "den-led",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1LeZqPFbsP",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá với trang trí cung điện ánh sáng / Mô hình kiến trúc Trung Quốc Trang trí bể cá / Trang trí cung điện / Bể cá cảnh quan / Trang đá sân / Mô phỏng cảnh quan vi mô / Phụ hồ cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp21",
        "price":  "246,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1qaqRKDhrW",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Cảnh quan bể cá Vương quốc bí mật La Mã Mô hình in 3D / Cảnh quan hang động cột La Mã / Đền thờ ngầm cá và tôm / Nhà sơ tán cá và tôm / Trang trí hồ cá Hầm hang động Phụ kiện hồ cá / Trang trí bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp22",
        "price":  "74,8k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1gHQF1ELCV",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Nơi trú ẩn cá cảnh DELMER, Nơi ẩn náu dưới nước bằng nhựa Hang ẩn tôm cá, Rùa nhiều lỗ độc đáo Cảnh quan hình rùa rỗng cảnh quan bể cá cảnh quan"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp23",
        "price":  "38,5k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2BDgpwCRBc",
        "status":  "active",
        "rating":  "5.0",
        "title":  "WAPKTY Giá đỡ thực vật bể cá treo, Chậu cảnh quan thủy canh Bể cá Giỏ trồng thủy canh, Giá trồng cây cảnh cảnh cảnh quan cây nước Giá trồng cây cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp24",
        "price":  "88,8k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/20uGddD4Wb",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Hồ Nhiều Loại Nhựa Mô Hình Cá Đồ Chơi Nhân Vật Cho Cá Cảnh Quan Mô Hình Cá Phong Cảnh Bể Cá Bàn Làm Việc Cá Bát Dec"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Đèn LED \u0026 Thủy Sinh",
        "id":  "csv-sp25",
        "price":  "435,6k",
        "category":  "den-led",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2VqXEYBAVi",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể Cá Kẹp Ánh Sáng Bể Cá Cảnh Quan Ánh Sáng Trang Trí Cá Nhỏ Bể Cá Kẹp Ánh Sáng Cảnh Quan Bể Cá Sáng Sáng Kẹp Nhỏ Ánh Sáng Xanh Trắng 6.4"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp26",
        "price":  "80,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2LX72FBnqh",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Nấm Thái Bio Knock Cho Cá Cảnh Hỗ Trợ Chăm Sóc Cá, Dùng Cho Cá Koi, Cá Betta, Cá Cảnh Nước Ngọt."
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp27",
        "price":  "45,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8AUtyxpb0q",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Giỏ trồng thủy canh bể cá NELO, Lưu vực cảnh quan thủy canh Treo giá đỡ thực vật bể cá, Giá trồng cây cảnh cảnh cảnh quan cây nước Giá trồng cây cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp28",
        "price":  "107,4k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/80BTmeqELp",
        "status":  "active",
        "rating":  "5.0",
        "title":  "RAN Phụ kiện bể cá không phai màu Hộp đựng cá xốp 2 chiếc Hộp đựng cá cảnh in hình 3d Nơi trú ẩn cá - Hang ẩn cá bền với nhiều lỗ Hoàn hảo cho cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp29",
        "price":  "66,7k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8V7kNZoKKw",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan/bể cá đáy cát cảnh quan/bể cá mô phỏng nghiền đá cảnh quan/tự nhiên đầy màu sắc pha lê đá trang trí/acrylic sáng tạo đầy màu sắc đáy đá bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp30",
        "price":  "145,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8KoKBGoxfv",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Trang trí cảnh quan bể cá, cảnh quan sinh thái, trang trí cảnh quan bể cá, cảnh quan nhân tạo, cảnh quan nhựa, trang trí mini N2HD"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp31",
        "price":  "165,5k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8pkamBn3f2",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá xương cá sấu / Xương di chuyển bản lề đồ chơi Bể cá cảnh quan trang trí / trang trí máy tính để bàn / trang trí hồ cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp32",
        "price":  "41,4k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8fRAZsnh01",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Eshylala Bể Cá Trang Trí Mô Phỏng Thực Vật Thủy Sinh Cảnh Quan Cá Cảnh Cá Cá Cỏ Nhân Tạo Phụ Kiện Bể Cá Eshylala"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp33",
        "price":  "161,8k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9ANRAnlmz8",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể Cá Lớn Thành Phẩm Trọn Gói Cảnh Quan Bể Cá Rockery Cảnh Quan Bể Cá Trang Trí Rockery Đá Bể Cá Cảnh Quan Đá 26..WTZ2"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp34",
        "price":  "39,1k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1520301255226-bf5f144451c1?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9040yUmQK7",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Lồng Đẻ Cá Guppy Mica Trong Suốt Lồng Cá Đôi Tách Cá Dưỡng Bệnh Khay Ép Cá Đẻ Cá Cảnh Tép Cảnh #"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp35",
        "price":  "42,7k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9V0HZPkWJE",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bighsm Bể Cá Trang Trí Mô Phỏng Thủy Sinh Thực Vật Cảnh Quan Cá Cảnh Cá Cá Nhân Cỏ Nhân Tạo Phụ Kiện Bể Cá SKK"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp36",
        "price":  "39,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9KgrN6l9eD",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Metoo Câu Cá Mèo Bể Cá Trang Trí Bể Cá Hangable Cảnh Quan Bể Cá Mèo Câu Cá Trang Trí Nhà Trang Trí Bể Cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp37",
        "price":  "41,2k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9pd7y1jFdK",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh cá mập nổi trang trí bể cá dễ thương khốc liệt Cá mập trắng lớn cá mập nhỏ cảnh quan thủ công"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp38",
        "price":  "140,6k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9fJhlijsyJ",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá trang trí/sáng tạo lá sen nổi rùa câu cá trang trí trang trí/bể cá bể cá rockery nước chảy ao cá sân cảnh quan con lắc/bể cá trang trí trang trí"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp39",
        "price":  "88,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/AAFyMdhyxQ",
        "status":  "active",
        "rating":  "5.0",
        "title":  "REBLUE Cá Tôm Ẩn Hang, Thân Cây Độc Đáo Bể Cá Nơi Trúng Cá, Trang Trí 3D In Hình Gỗ Trôi Cảnh Quan Bể Cá Cảnh Quan Cảnh Quan"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp40",
        "price":  "110,6k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9zwYAKicIP",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Hang đá hình học nhựa / bể cá nhà trú ẩn cảnh quan / bể cá nhỏ và tôm ẩn / trang trí bể cá / trang trí bể cá / cảnh quan bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp41",
        "price":  "45,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/AUsolFgiHW",
        "status":  "active",
        "rating":  "5.0",
        "title":  "C5GOON Câu Cá Mèo Bể Cá Trang Trí Bể Cá Có Thể Treo Phong Cảnh Bể Cá Mèo Câu Cá Trang Trí Nhà Bể Cá Trang Trí I7N2"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp42",
        "price":  "69,6k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/AKZOYwhLcV",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Mô phỏng động vật biển cá mô hình đồ chơi cá hồi cá hồi cá hồi miệng lớn bass cá ngừ bể cá cảnh trang trí"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp43",
        "price":  "45,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/5VU8o3zkQa",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Trị đốm trắng cá cảnh Biozym White Spot Conditioner – Hỗ Trợ trị đốm trắng cho cá cảnh Cá Cảnh Thiên Phước"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp44",
        "price":  "379,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/5LAibl0NlZ",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh, bể cá sinh thái cảnh quan gia đình, bể cá nhựa, cảnh quan để bàn cỡ nhỏ và vừa MXPF009"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp45",
        "price":  "32,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/5q6zCfyTkg",
        "status":  "active",
        "rating":  "5.0",
        "title":  "[SHgeZm] Nhà xà cừ nấm Nơi trú ẩn Bể cá Cảnh quan Trang trí bể cá Trang trí bể cá Trang trí bể cá Nơi trú ẩn cá [MỚI]"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp46",
        "price":  "40,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1516683011827-46882e75a351?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/5fnZ0Mz75f",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Đồ Chơi Thuỷ Sinh Cho Cá Cảnh Tép Cảnh- Đồ chơi trang trí hồ tép cảnh cá cảnh thuỷ sinh"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp47",
        "price":  "110,7k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/6AjpbHxD4m",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá trang trí / Micro cảnh quan đá cảnh quan trang trí / Arch cầu mô hình kiến trúc cổ xưa / Nước và đất cá bể cảnh quan / kiểu Trung Quốc kiểu mô hình viện"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp48",
        "price":  "65,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/60QPOyxqPl",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Hộp ấp trứng cá cảnh, hộp cách ly sinh sản cá bảy màu, trứng và cá con nhỏ, cá vằn, vật tư bể cá betta"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp49",
        "price":  "190,5k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/6VMfztvwOs",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan, nhà trú ẩn bể cá gốm, lỗ thoát cá và tôm, đường hầm thoát cá, hình ảnh sinh sản cá trang trí cảnh quan"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp50",
        "price":  "5,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/6L3FnawZjr",
        "status":  "active",
        "rating":  "5.0",
        "title":  "  Tiểu Cảnh Charm Đuôi Cá Trí Hồ Cá, Bể Cá, Chậu Cây, Tiểu Cảnh Terrarium [ĐUÔI CÁ]"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp51",
        "price":  "375,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/6pzWOVufiy",
        "status":  "active",
        "rating":  "5.0",
        "title":  "hồ cá cảnh, bể cá sinh thái cảnh quan gia đình, bể cá nhựa, cảnh quan để bàn cỡ nhỏ và vừa MXPF009"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp52",
        "price":  "44,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/6fg6CCvJ3x",
        "status":  "active",
        "rating":  "5.0",
        "title":  "THUY Treo Bể Cá Giá Đỡ, Chậu Cảnh Quan Bể Trồng Bể Cá Giỏ Trồng Thủy Canh, Phong Cảnh Cây Nước Thủy Bể Cá Cây Cốc Cho Bể Cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp53",
        "price":  "58,8k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/7AcMn7tP34",
        "status":  "active",
        "rating":  "5.0",
        "title":  "( Mẫu mới )Mô hình cây cầu tiểu cảnh trang trí bể cá cảnh, bể cá mini, trang trí hòn non bộ. Tiểu cảnh trang trí bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp54",
        "price":  "45,5k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/70Iwaou2O3",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá mini, bể cá trong suốt, bể cá nhựa, bể cá cảnh, nhiều kích cỡ, chỉ có bể cá rỗng MXP0099"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp55",
        "price":  "31,4k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/7VFDBjs8NA",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Cây Nhựa Thủy Sinh Cỡ Lớn Trang Trí Bể Cá - Hồ Cá Cảnh - Cây Cảnh Thủy Sinh Giả Tiểu Cảnh Trang Trí Bể Cá Sống Động"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp56",
        "price":  "111,8k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/7KvmzQsli9",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá trang trí trang trí / Sàn quan sát kiến trúc cổ đại micro cảnh quan tinh tế nhà nhỏ / Nước và đất cá bể đá / Bonsai micro cảnh quan trang trí cảnh quan trang trí"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp57",
        "price":  "15,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/7ps3aLqrhG",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Tiểu cảnh Mèo Câu Cá  - Tiểu Cảnh Trang Trí Hồ Cá, Bể Cá Thủy Sinh Xinh Đẹp [MÈO CÂU CÁ]"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp58",
        "price":  "106,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/7fYdO2rV2F",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Cảnh quan bể cá / Trang trí hồ cá / Giai đoạn đá cổ, mô hình kiến trúc cổ đại Trung Quốc, trang trí bonsai nước và đất / Cảnh quan bể cá kiến trúc cổ đại, phong cách Trung Quốc / Cảnh quan bể cá phong cách Trung Quốc"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp59",
        "price":  "150,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2g9xQrAXBI",
        "status":  "active",
        "rating":  "5.0",
        "title":  "[NEW GEN]Vi sinh BIOMIX-PLUS (dành cho cá cảnh) cá cảnh, cá betta, hồ cá. Đại lý chính thức Cty AQUA"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp60",
        "price":  "32,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2qTNdA9tqL",
        "status":  "active",
        "rating":  "5.0",
        "title":  "\u003c SDJZT \u003e Nhà ốc xà cừ nấm Nơi trú ẩn Bể cá Cảnh quan Trang trí bể cá Trang trí bể cá Trang trí bể cá Nơi trú ẩn cá đang được bán"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp61",
        "price":  "139,6k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/30mnpT9GVO",
        "status":  "active",
        "rating":  "5.0",
        "title":  "*Từ Tính Bể Cá Lưới Chống Nhảy Chống Cảnh Quan Bể Cá Tiếp Liệu Tách Bể Cá Phân Vùng Bể Cá Cách Ly Ban Bể Cá Chống Va Đập"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp62",
        "price":  "85,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/3B6E1m8dAR",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Mô Hình Tiểu Cảnh Cầu Non Bộ - Cối Xay Nước Trang Trí Bể Cá Phụ Kiện Bể Cá Cảnh Mini Tiểu Cảnh Đá Mini Trang Trí Bể Cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp63",
        "price":  "12,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/3LPeE57zpU",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Cá trang trí bể cá cảnh thủy sinh ( lấy ngẫu nhiên)- Cá giả bằng nhựa thả bể cá cảnh thủy sinh"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp64",
        "price":  "79,0k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/3Vj4QO7MUX",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Xử Lý Cá Cảnh Xù Vảy, Sốt Huyết, Đục Mắt, Nấm Trắng, Nấm Đen | Cá Rồng, Cá Chép, Cá Vàng, Cá Koi,vv"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp65",
        "price":  "107,2k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/3g2Uch6j9a",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / trang trí hồ cá trang trí / mô phỏng thực vật nước cảnh tinh thể cột trắng whisker san hô cá bể cá trang trang trí / phụ kiện trang hồ cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp66",
        "price":  "15,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/3qLup065od",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Cá sấu dễ thương trang trí bể cá cảnh, trang trí tiểu cảnh, bể thủy sinh, bể cá mini, bể cá để bàn"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp67",
        "price":  "63,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/40fL1J5STg",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá trang trí trang trí / Nhựa câu cá ông già câu cá bể cá trang trí trang trí nhỏ / treo câu cá ông già trang trí"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Đèn LED \u0026 Thủy Sinh",
        "id":  "csv-sp68",
        "price":  "309,7k",
        "category":  "den-led",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4AylDc4p8j",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Betta Bể Cá Cảnh Quan Nhỏ Sinh Thái Cá Giống Cá Đặc Biệt Với Ánh Sáng Sáng Sáng Tạo Cá Vàng Xe Tăng Để Bàn Bể Cá Nhỏ"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp69",
        "price":  "25,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4LIBPv4Bnm",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Calcium Max Bù Khoáng Cá Cảnh | Khoáng Cá Cảnh Giúp Cá Lên Màu Đẹp Khỏe Mạnh Kích Sinh Sản Cho Hồ Cá Thủy Sinh."
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp70",
        "price":  "79,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4VbbcE3YSp",
        "status":  "active",
        "rating":  "5.0",
        "title":  "DTW 12 Chiếc Cá Nhiệt Đới Phụ Kiện Bể Cá Di Chuyển Nhân Tạo Cá Nhựa Nổi Cá Nhỏ Bể Cá Mô Phỏng Sống Động Phong Cảnh Thể Thao"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp71",
        "price":  "102,2k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4fv1oX2v7s",
        "status":  "active",
        "rating":  "5.0",
        "title":  "NS Bể Cá Thùng Trang Trí Cá Tôm Nơi Trú Ẩn Cá Nhựa Thùng Đồ Trang Trí Cá Và Tôm Ẩn Hang Bể Cá Cảnh Quan NS"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp72",
        "price":  "144,4k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/4qES0q2Hmv",
        "status":  "active",
        "rating":  "5.0",
        "title":  " Bộ phụ kiện trang trí cảnh quan bể cá nhỏ, thuyền mini mô phỏng kèm vòng bơi, mèo câu cá và người câu cá, thiết kế bố trí nổi cảnh quan bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp73",
        "price":  "4,4tr",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/50XsD91eRy",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Hồ cá 3 tầng, hồ cá mini, bể cá phong thủy, tiểu cảnh ban công, hồ cá thác nước, hồ cá thủy sinh"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp74",
        "price":  "120,5k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/5ArIPS1171",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Trang trí hồ cá / Trang trí sáng tạo cho trang trí bể cá In 3D bể trốn thoát hình cầu / Bể trốn thoát cá và tôm / Bể sinh sản lỗ sinh sản cá nhỏ / Trang trí bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp75",
        "price":  "50,2k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/19CFxKgb2",
        "status":  "active",
        "rating":  "5.0",
        "title":  "GAOXI75 Giá đỡ thực vật bể cá treo, Lưu vực cảnh quan Cây nước Cảnh quan Bể cá Giỏ trồng thủy canh, Bể trồng thủy canh Cốc trồng bể cá cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp76",
        "price":  "119,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/BScSGK3G5",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Cảnh quan bể cá / Trang trí hồ cá / Cảnh quan vi mô với kiến trúc chiếu sáng Cảnh quan phong cách Trung Quốc / Cảnh quan bể cá đá, nước và đất liền bonsai / Mô hình nhà mô phỏng sản phẩm hoàn thành"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp77",
        "price":  "195,6k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/Lm2eZJPv8",
        "status":  "active",
        "rating":  "5.0",
        "title":  "NS Mini Hành Trình Dễ Thương Đến Phương Tây Master Và Người Học Việc Đồ Trang Trí Bốn Người Phong Cảnh Giả Cây Cảnh Bể Cá Cảnh Quan Đồ Trang Trí Bể Cá Micro Phong Cảnh NS"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp78",
        "price":  "52,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/W5SqsImaB",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Giỏ trồng thủy canh bể cá HEARTHLY, Cây nước thủy canh treo cảnh quan Giá đỡ thực vật bể cá, Chậu trồng cảnh quan bể cá Cốc trồng cây cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp79",
        "price":  "55,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/gOt3BI9FE",
        "status":  "active",
        "rating":  "5.0",
        "title":  "[COD] Giỏ trồng thủy canh bể cá, Bể trồng cảnh quan cây nước treo bể cá, Chậu cảnh quan Bể cá thủy canh Cốc trồng cây cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp80",
        "price":  "32,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/qiJFUHVuH",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Tiểu cảnh Ông Lão Ngồi Câu Cá Trang Trí Bể Cá, Bể Thủy Sinh Tiểu Cảnh non bộ tiểu cảnh hồ cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp81",
        "price":  "77,8k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/111jRnGsZK",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Hftoy 12 Chiếc Cá Nhiệt Đới Phụ Kiện Bể Cá Di Chuyển Cá Nhân Tạo Nhựa Nổi Cá Nhỏ Bể Cá Mô Phỏng Phong Cảnh Sống Động ~"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp82",
        "price":  "86,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1BL9e6GFEN",
        "status":  "active",
        "rating":  "5.0",
        "title":  "TRTR Bể Cá Thùng Trang Trí Cá Tôm Nơi Trú Ẩn Cá Nhựa Thùng Đồ Trang Trí Cá Và Tôm Ẩn Hang Bể Cá Cảnh Quan VN"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp83",
        "price":  "187,5k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1LeZqPFbtQ",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá chìm trang trí Fengtian Terrace / Micro cảnh quan bonsai trang trí trang trí / Rocky cổ kiến trúc cảnh quan / trang hồ cá / cảnh quan bể cá / trang bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp84",
        "price":  "45,7k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1Vy02iEyYT",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Giỏ trồng thủy canh bể cá ORIENRI, Chậu cảnh quan bể trồng cây treo bể cá, Chậu cây thủy canh Cảnh quan bể cá cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp85",
        "price":  "135,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1gHQF1ELDW",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Trang trí cảnh quan vi mô / Bể cá Qianli Jiangshan gốm đá trang trí / Trang trí nội thất văn phòng / Bể cá cảnh quan"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp86",
        "price":  "51,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/1qaqRKDhsZ",
        "status":  "active",
        "rating":  "5.0",
        "title":  "CATIYAHA Treo Cây Bể Cá, Cây Nước Thủy Canh Cảnh Quan Bể Cá Thủy Canh Giỏ Trồng Thủy Canh, Chậu Cảnh Quan Bể Trồng Bể Cá Cốc Cho Bể Cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp87",
        "price":  "50,1k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/20uGddD4Xc",
        "status":  "active",
        "rating":  "5.0",
        "title":  "FURNIGO Giá đỡ thực vật bể cá treo, Bể trồng cảnh quan cây nước Bể cá Giỏ trồng thủy canh, Chậu cảnh quan Bể cá thủy Cốc trồng cây cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp88",
        "price":  "92,3k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2BDgpwCRCf",
        "status":  "active",
        "rating":  "5.0",
        "title":  "ZICHUE Cá Trang Trí Bể Cá Thực Vật Cảnh Quan Dưới Nước Cho Bể Cá Trang Trí Cảnh Quan Cá Cung Cấp Cây Nhân Tạo"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp89",
        "price":  "86,0k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2LX72FBnri",
        "status":  "active",
        "rating":  "5.0",
        "title":  "TATER Bể Cá Thùng Trang Trí Cá Tôm Nơi Trú Ẩn Cá Nhựa Thùng Đồ Trang Trí Cá Và Tôm Ẩn Hang Bể Cá Cảnh Quan VN"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp90",
        "price":  "51,8k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/2VqXEYBAWl",
        "status":  "active",
        "rating":  "5.0",
        "title":  "IBORAGE Bể Cá Thủy Canh Giỏ Trồng, Lưu Vực Cảnh Quan Treo Thủy Canh Giá Đỡ Thực Vật Bể Cá, Bể Trồng Nước Cảnh Quan Cây Trồng Bể Cá Cốc Cho Bể Cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp91",
        "price":  "81,4k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/80BTmeqEMq",
        "status":  "active",
        "rating":  "5.0",
        "title":  "GKY 12 Chiếc Cá Nhiệt Đới Phụ Kiện Bể Cá Di Chuyển Nhân Tạo Cá Nhựa Nổi Cá Nhỏ Bể Cá Mô Phỏng Sống Động Phong Cảnh GKY"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp92",
        "price":  "148,1k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8AUtyxpb1t",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan gian / Bể cá trang trí gian mới / Kiến trúc cổ Trung Quốc retro trang trí phong cách Trung Quốc / Mô hình kiến trúc cổ xưa / Bể cá đá / Bonsai trang cảnh quan / Bể cá trang trang trí"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp93",
        "price":  "53,7k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8KoKBGoxgw",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Giỏ trồng thủy canh bể cá SIRENXI, Lưu vực cảnh quan Bể trồng cây treo Giá đỡ thực vật bể cá, Bình đựng cá thủy canh cảnh quan thực vật nước cho bể cá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Đèn LED \u0026 Thủy Sinh",
        "id":  "csv-sp94",
        "price":  "203,8k",
        "category":  "den-led",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8V7kNZoKLz",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Bể cá cảnh quan / Bể cá trang trí / Kiến trúc cảnh quan với ánh sáng / Zen lấy cảm hứng cảnh quan vi mô của bể cá / Micro phòng trà trang trí bàn trà / Bonsai trang trí"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Thuốc \u0026 Men Vi Sinh",
        "id":  "csv-sp95",
        "price":  "32,8k",
        "category":  "thuoc-men",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8fRAZsnh12",
        "status":  "active",
        "rating":  "5.0",
        "title":  "BBLUE Nấm Conch Nhà Nơi trú ẩn Bể cá Cảnh quan Trang trí cá Trang trí cá Trang trí cá Nơi trú ẩn cá."
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp96",
        "price":  "119,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/8pkamBn3g5",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Little Fairy \u0027s Yêu Thích Trang Trí Bể Cá Ngọc Trai Hạt Thủy Tinh Gói Cô Gái Màu Hồng Ảo Tím Nhiều Màu Sắc Hạt Thủy Tinh Tự Làm Trang Trí Cảnh Quan Bể Cá Hạt Thủy Tinh Nhiều Màu Sắc Bể Cá Cảnh Quan Sáng Tạo Betta Bể Cá Hạt Thủy Tinh Đáy Cát Đá"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp97",
        "price":  "21,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9040yUmQL8",
        "status":  "active",
        "rating":  "5.0",
        "title":  "San hô mini trang trí cảnh quan bể cá cảnh , thủy sinh, bể cá biển- đồ trang trí decor bể cá cảnh thủy sinh"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp98",
        "price":  "101,2k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9ANRAnln0B",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Nàng Tiên Cá Treo Bể Cá Cảnh Quan Trang Trí Đồ Trang Trí Bể Cá Gia Đình Bể Cá Micro Phong Cảnh Dễ Thương Chìm"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp99",
        "price":  "164,6k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9KgrN6l9fE",
        "status":  "active",
        "rating":  "5.0",
        "title":  "Vip Sea Shipwreck Trang trí bể cá Trang trí bể cá bằng nhựa Trang trí tàu chìm với lỗ rỗng Trang trí cảnh quan bể cá cho rùa tôm cá Nơi ẩn náu – Bể cá bền"
    },
    {
        "originalPrice":  "Shopee Deal",
        "categoryName":  "Phụ Kiện Bể Cá",
        "id":  "csv-sp100",
        "price":  "42,9k",
        "category":  "phu-kien",
        "discount":  "HOT",
        "sold":  "Shopee Mall",
        "image":  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500\u0026auto=format\u0026fit=crop\u0026q=80",
        "shopeeUrl":  "https://s.shopee.vn/9V0HZPkWKH",
        "status":  "active",
        "rating":  "5.0",
        "title":  "WUAWUA Giỏ trồng thủy canh bể cá, Bể trồng thủy canh Treo cây cảnh, Chậu cảnh quan Cây cảnh Cây nước Cảnh quan Giá trồng cây cho bể cá"
    }
];
